version: '3.7'
services:
  exchange:
    container_name: exchange
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      - SERVER_PORT=8000
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_ZIPKIN_BASE_URL=zipkin:9411
    depends_on:
      - zipkin
      - rabbitmq
    networks:
      - microservices-network
  conversion:
    container_name: conversion
    build:
      context: ../currency-conversion-service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    restart: always
    environment:
      SERVER_PORT: 8100
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672
      SPRING_ZIPKIN_BASE_URL: zipkin:9411
      CURRENCY_EXCHANGE_SERVICE_ADDRESS: http://exchange:8000
    depends_on:
      - zipkin
      - rabbitmq
    networks:
      - microservices-network
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    restart: always
    networks:
      - microservices-network
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    ports:
      - "5672:5672"
    restart: always
    networks:
      - microservices-network
networks:
  microservices-network:



